name: Scrape Jumia Prices

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: # allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install playwright playwright-stealth
          playwright install --with-deps chromium

      # Run scraper
      - name: Run scraper
        run: python jumia_scraper.py

      # Commit and force push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add prices.json
          git commit -m "Update prices [skip ci]" || echo "No changes to commit"
          git pull --rebase --strategy-option=theirs origin main
          git push origin main --force
