name: Scrape commodity prices

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright==1.45.0 playwright-stealth==1.0.6
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if prices.json changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main
          git add prices.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update prices" && git push)
