name: Scrape Prices

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # so we can pull without conflicts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright playwright-stealth
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes to avoid conflicts
        run: |
          git pull origin main --rebase || true

      - name: Commit and push if changed
        run: |
          git add prices.json
          if git diff --cached --quiet; then
            echo "No changes in prices.json, skipping commit."
          else
            git commit -m "Update prices"
            git push origin main
          fi
