name: Scrape Jumia Prices

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch: # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important so we can pull/rebase

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.47.0
          pip install playwright-stealth
          playwright install --with-deps chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updated prices.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git fetch origin main
          git checkout main
          git pull --rebase origin main || true

          git add prices.json
          git diff --cached --quiet || git commit -m "Update prices"

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main --force
